/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import models.Students;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import controllers.StudentsDAO;

/**
 *
 * @author phuho
 */
public class StudentsFrame extends javax.swing.JFrame {

    /**
     * Creates new form StudentsFrame
     */
    DefaultTableModel model;
    String pathLblIcon = null;
    private StudentsDAO studentsDAO;

    public StudentsFrame() {
        initComponents();
        model = (DefaultTableModel) table_main.getModel();

        this.getContentPane().setBackground(Color.CYAN);
        Border border = BorderFactory.createMatteBorder(4, 4, 4, 4, Color.cyan);
        btn_new.setBorder(border);
        btn_save.setBorder(border);
        btn_delete.setBorder(border);
        btn_update.setBorder(border);

        JTableHeader header = table_main.getTableHeader();
        header.setFont(new Font("SansSerif", Font.BOLD, 16));

        try {
            studentsDAO = new StudentsDAO();
            if (!studentsDAO.get().isEmpty()) {
                loadListToTable(studentsDAO.get());
                setStudentToInput(0);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Message", JOptionPane.ERROR_MESSAGE);
        }

    }

    public void loadListToTable(ArrayList<Students> list) {
        model.fireTableDataChanged(); // fix: WARNING: row index is bigger than sorter's row count   
        model.setRowCount(0);
        for (Students s : list) {
            model.addRow(new Object[]{
                s.getMaSV(),
                s.getHoTen(),
                s.getEmail(),
                s.getSoDT(),
                rGT(s.getGioiTinh()),
                s.getDiaChi(),
                s.getHinhAnh()
            });
        }
    }

    public String rGT(int t) {
        if (t == 1) {
            return "Nam";
        }
        return "Nữ";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btn_new = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_main = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_masv = new javax.swing.JTextField();
        txt_hoten = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_sdt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rdo_nam = new javax.swing.JRadioButton();
        rdo_nu = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_diachi = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        lbl_img = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản lý sinh viên");
        setResizable(false);

        btn_new.setBackground(new java.awt.Color(255, 255, 51));
        btn_new.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_new.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plus-6-16.png"))); // NOI18N
        btn_new.setText("NEW");
        btn_new.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_new.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_newMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_newMouseExited(evt);
            }
        });
        btn_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newActionPerformed(evt);
            }
        });

        btn_save.setBackground(new java.awt.Color(255, 255, 51));
        btn_save.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save-16.png"))); // NOI18N
        btn_save.setText("SAVE");
        btn_save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_newMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_newMouseExited(evt);
            }
        });
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_delete.setBackground(new java.awt.Color(255, 255, 51));
        btn_delete.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete-16.png"))); // NOI18N
        btn_delete.setText("DELETE");
        btn_delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_newMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_newMouseExited(evt);
            }
        });
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_update.setBackground(new java.awt.Color(255, 255, 51));
        btn_update.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit-2-16.png"))); // NOI18N
        btn_update.setText("UPDATE");
        btn_update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_newMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_newMouseExited(evt);
            }
        });
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        table_main.setAutoCreateRowSorter(true);
        table_main.setBackground(new java.awt.Color(102, 255, 255));
        table_main.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        table_main.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã SV", "Họ tên", "Email", "Số ĐT", "Giới tính", "Địa chỉ", "Hình"
            }
        ));
        table_main.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        table_main.setFillsViewportHeight(true);
        table_main.setRowHeight(27);
        table_main.setSelectionBackground(new java.awt.Color(0, 0, 102));
        table_main.setSelectionForeground(new java.awt.Color(255, 255, 153));
        table_main.setShowGrid(false);
        table_main.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_mainMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_main);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Mã SV");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 102));
        jLabel2.setText("QUẢN LÝ SINH VIÊN");

        txt_masv.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txt_hoten.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Họ tên");

        txt_email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Email");

        txt_sdt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Số ĐT");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Giới tính");

        buttonGroup1.add(rdo_nam);
        rdo_nam.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rdo_nam.setText("Nam");
        rdo_nam.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        buttonGroup1.add(rdo_nu);
        rdo_nu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        rdo_nu.setText("Nữ");
        rdo_nu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Địa chỉ");

        txt_diachi.setColumns(20);
        txt_diachi.setRows(5);
        jScrollPane1.setViewportView(txt_diachi);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lbl_img.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_img.setText("Chọn ảnh đại diện");
        lbl_img.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_img.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_imgMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_img, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_img, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(195, 195, 195))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_masv, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdo_nam)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdo_nu)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_new, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_masv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(rdo_nam)
                            .addComponent(rdo_nu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txt_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_new, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_newMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_newMouseEntered
        String a = evt.getSource().toString();

        if (a.contains("text=NEW")) {
            btn_new.setBackground(new Color(169, 200, 2));
        } else if (a.contains("text=DELETE")) {
            btn_delete.setBackground(new Color(169, 200, 2));
        } else if (a.contains("text=UPDATE")) {
            btn_update.setBackground(new Color(169, 200, 2));
        } else if (a.contains("text=SAVE")) {
            btn_save.setBackground(new Color(169, 200, 2));
        }
    }//GEN-LAST:event_btn_newMouseEntered

    private void btn_newMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_newMouseExited
        String a = evt.getSource().toString();

        if (a.contains("text=NEW")) {
            btn_new.setBackground(new Color(255, 255, 51));
        } else if (a.contains("text=DELETE")) {
            btn_delete.setBackground(new Color(255, 255, 51));
        } else if (a.contains("text=UPDATE")) {
            btn_update.setBackground(new Color(255, 255, 51));
        } else if (a.contains("text=SAVE")) {
            btn_save.setBackground(new Color(255, 255, 51));
        }
    }//GEN-LAST:event_btn_newMouseExited

    private void table_mainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_mainMouseClicked
        int t = table_main.getSelectedRow();
        if (t >= 0) {
            setStudentToInput(t);
        }
    }//GEN-LAST:event_table_mainMouseClicked

    private void btn_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newActionPerformed
        resetAll();
    }//GEN-LAST:event_btn_newActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        if (checkAll()) {
            try {
                Students s = getStudent();
                studentsDAO.insert(s);
                ArrayList<Students> list = studentsDAO.get();
                resetAll();
                loadListToTable(list);
                JOptionPane.showMessageDialog(this, "Thêm thành công!", "Message", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "Message", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void lbl_imgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_imgMouseClicked
        JFileChooser file = new JFileChooser("src\\img");
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images", "jpg", "gif", "png");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = file.getSelectedFile();
            pathLblIcon = selectedFile.getAbsolutePath();
            lbl_img.setText("");
            lbl_img.setIcon(ResizeImage(pathLblIcon));
            pathLblIcon = pathLblIcon.substring(pathLblIcon.lastIndexOf("\\") + 1);
        }
    }//GEN-LAST:event_lbl_imgMouseClicked

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        try {
            if (studentsDAO.get().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Danh sách sinh viên rỗng", "Message", JOptionPane.INFORMATION_MESSAGE);
            } else if (table_main.getSelectedRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Hãy chọn SV cần xóa", "Message", JOptionPane.INFORMATION_MESSAGE);
            } else {
                try {
                    int prompt = JOptionPane.showConfirmDialog(this, "Bạn có chắc xóa không?", "Message", JOptionPane.INFORMATION_MESSAGE);
                    if (prompt == 0) {
                        studentsDAO.delete(txt_masv.getText().trim());
                        ArrayList<Students> list = studentsDAO.get();
                        resetAll();
                        loadListToTable(list);
                        JOptionPane.showMessageDialog(this, "Xóa thành công!", "Message", JOptionPane.INFORMATION_MESSAGE);
                        if(!list.isEmpty()) setStudentToInput(0);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e.getMessage(), "Message", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Message", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        try {
            if(studentsDAO.get().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Danh sách sinh viên rỗng", "Message", JOptionPane.INFORMATION_MESSAGE);
            } else if (table_main.getSelectedRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Hãy chọn SV cần cập nhật", "Message", JOptionPane.INFORMATION_MESSAGE);
            } else if (checkAll()){
                try {
                    Students s = getStudent();
                    studentsDAO.update(s, txt_masv.getText().trim());
                    ArrayList<Students> list = studentsDAO.get();
                    int t = table_main.getSelectedRow();
                    loadListToTable(list);
                    setStudentToInput(t);
                    JOptionPane.showMessageDialog(this, "Cập nhật thành công!", "Message", JOptionPane.INFORMATION_MESSAGE);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e.getMessage(), "Message", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (Exception e) {
        }
        
        
    }//GEN-LAST:event_btn_updateActionPerformed

    public Students getStudent() throws Exception {
        Students s = new Students();
        s.setMaSV(txt_masv.getText());
        s.setHoTen(txt_hoten.getText());
        s.setEmail(txt_email.getText());
        s.setSoDT(txt_sdt.getText());
        s.setDiaChi(txt_diachi.getText());
        s.setHinhAnh(pathLblIcon);
        int gt;
        if (rdo_nam.isSelected()) {
            gt = 1;
        } else {
            gt = 0;
        }
        s.setGioiTinh(gt);
        return s;
    }

    public boolean checkAll() {
        if (txt_masv.getText().trim().equals("")
                || txt_hoten.getText().trim().equals("")
                || txt_email.getText().trim().equals("")
                || txt_sdt.getText().trim().equals("")
                || txt_diachi.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tất cả thông tin", "Message", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        if (txt_sdt.getText().length() < 10 || txt_sdt.getText().length() > 13) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập sđt từ 10-13 kí tự", "Message", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        if (!rdo_nam.isSelected() && !rdo_nu.isSelected()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn giới tính", "Message", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        if (lbl_img.getIcon() == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn hình đại diện", "Message", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        return true;
    }

    public void resetAll() {
        table_main.clearSelection();
        txt_masv.setText("");
        txt_hoten.setText("");
        txt_email.setText("");
        txt_sdt.setText("");
        txt_diachi.setText("");
        buttonGroup1.clearSelection();
        lbl_img.setIcon(null);
        lbl_img.setText("Chọn ảnh đại diện");
    }

    public void setStudentToInput(int t) {
        table_main.setRowSelectionInterval(t, t);

        txt_masv.setText(table_main.getValueAt(t, 0).toString());
        txt_hoten.setText(table_main.getValueAt(t, 1).toString());
        txt_email.setText(table_main.getValueAt(t, 2).toString());
        txt_sdt.setText(table_main.getValueAt(t, 3).toString());
        txt_diachi.setText(table_main.getValueAt(t, 5).toString());

        String gt = table_main.getValueAt(t, 4).toString();
        String img = table_main.getValueAt(t, 6).toString();
        lbl_img.setIcon(ResizeImage("src\\img\\" + img));
        pathLblIcon = img;
        if (gt.equals("Nam")) {
            rdo_nam.setSelected(true);
        } else {
            rdo_nu.setSelected(true);
        }
    }

    public ImageIcon ResizeImage(String ImagePath) {
        lbl_img.setText("");
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(lbl_img.getWidth(), lbl_img.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_new;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_update;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_img;
    private javax.swing.JRadioButton rdo_nam;
    private javax.swing.JRadioButton rdo_nu;
    private javax.swing.JTable table_main;
    private javax.swing.JTextArea txt_diachi;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_hoten;
    private javax.swing.JTextField txt_masv;
    private javax.swing.JTextField txt_sdt;
    // End of variables declaration//GEN-END:variables
}
